Algoritmo "Exercicio_08"

Var
   distanciaM: real
Inicio
   escreva("Digite uma distância em METRO: ")
   leia(distanciaM)
   escreval("A distância de ", distanciaM, "m corresponde a:")
   escreval((distanciaM/1000),"km")
   escreval((distanciaM/100),"hm")
   escreval((distanciaM/10),"dam")
   escreval((distanciaM*10),"dm")
   escreval((distanciaM*100),"cm")
   escreval((distanciaM*1000),"mm")
Fimalgoritmo